# Generated by Django 4.0.2 on 2022-04-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='featured_image',
            field=models.ImageField(blank=True, default='default_internship.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default_project.jpg', null=True, upload_to=''),
        ),
    ]
